version: '1.0.{build}.0'

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore src\LightCollections.sln

build:
  parallel: true
  project: 'src\LightCollections.sln'
  publish_nuget: true

test:
  # assemblies to test - optional
  assemblies:    
    - '**\*.tests.dll'
  
after_build:
  - cmd: nuget pack src\Blondin.LightCollections\Blondin.LightCollections.nuspec -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  path: 'Blondin.LightCollections*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: 1+N1+by19CK3uQqleN4DjNgU4lq+8vnJrHCg5hVjG3b/V1KUA4bwa3Y+PUDjuH6e
  artifact: /Blondin.LightCollections.*\.nupkg/
  skip_symbols: false
